<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/Academic_Performance_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/CodeVinayak/Student-Performance-Analysis-Machine-Learning/master/StudentsPerformance.csv"

df = pd.read_csv(url)

In [ ]:
df.head()

,gender,race,parental_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
# Task 2: Column Selection

In [ ]:
scores_subset = df[['gender', 'math_score', 'reading_score']]

In [ ]:
scores_subset.head()

   gender  math_score  reading_score
0  female          72             72
1  female          69             90
2  female          90             95
3    male          47             57
4    male          76             78

In [ ]:
# Task 3: Positional Indexing with .iloc

In [ ]:
middle_sample = df.iloc[10:20, df.columns.get_loc('math_score')]

middle_sample

10    58
11    40
12    65
13    78
14    50
15    69
16    88
17    18
18    46
19    54
Name: math_score, dtype: int64

In [ ]:
# Task 4: Label-Based Selection with .loc

In [ ]:
high_math_students = df.loc[df['math_score'] > 80, ['gender', 'writing_score']]

high_math_students

     gender  writing_score
2    female             93
6    female             92
16     male             86
34     male             82
35     male             79
..      ...            ...
979  female             94
981    male             78
987    male             76
990    male             75
995  female             95

[176 rows x 2 columns]

In [ ]:
# Task 5: Multi-Condition Filtering

In [ ]:
literacy_excellence = df[
    (df['reading_score'] > 75) &
    (df['writing_score'] > 70)
]

literacy_excellence.head()

,gender,race,parental_education,lunch,test_preparation_course,math_score,reading_score,writing_score
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92