<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

df = pd.read_csv(url)

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

Task 2 – Type Conversion using .astype()

In [ ]:
df["total_bill"] = df["total_bill"].astype("float64")
df["tip"] = df["tip"].astype("float64")

In [ ]:
df["size"] = df["size"].astype("int64")

In [ ]:
df["day"] = df["day"].astype("object")

In [ ]:
df.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

Task 3 – Semantic Transformation

In [ ]:
df["sex"] = df["sex"].map({"Male": "M", "Female": "F"})

In [ ]:
df["smoker"] = df["smoker"].map({"Yes": True, "No": False})

In [ ]:
df["sex"].value_counts()

sex
M    157
F     87
Name: count, dtype: int64

In [ ]:
df["smoker"].value_counts()

smoker
False    151
True      93
Name: count, dtype: int64

Task 4 – String Cleaning

In [ ]:
df["time"] = df["time"].str.lower()

In [ ]:
df["time"] = df["time"].str.strip()

In [ ]:
df["time"].unique()

array(['dinner', 'lunch'], dtype=object)