<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/Introduction_to_Pandas_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/CodeVinayak/Student-Performance-Analysis-Machine-Learning/master/StudentsPerformance.csv"

df = pd.read_csv(url)

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [ ]:
df.head()

,gender,race,parental_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
print(df.shape)

(1000, 8)

In [ ]:
print(df.columns)

Index(['gender', 'race', 'parental_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [ ]:
df.dtypes

gender                     object
race                       object
parental_education         object
lunch                      object
test_preparation_course    object
math_score                  int64
reading_score               int64
writing_score               int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   1000 non-null   object
 1   race                     1000 non-null   object
 2   parental_education       1000 non-null   object
 3   lunch                    1000 non-null   object
 4   test_preparation_course  1000 non-null   object
 5   math_score               1000 non-null   int64
 6   reading_score            1000 non-null   int64
 7   writing_score            1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB